version: '3.8'

services:
  # Servicio de la Base de Datos PostgreSQL
  db:
    build: ./database
    container_name: postgres_db
    environment:
      POSTGRES_DB: customerperson_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dbpasswordtestCS123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Servicio de Mensajería RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  # Microservicio de Clientes
  clients-app:
    build:
      context: ./microservice-clients
    container_name: clients-app
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/customerperson_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=dbpasswordtestCS123
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - db
      - rabbitmq

  # Microservicio de Cuentas y Movimientos
  accounts-app:
    build:
      context: ./microservice-accounts
    container_name: accounts-app
    restart: on-failure
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/customerperson_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=dbpasswordtestCS123
      - SPRING_RABBITMQ_HOST=rabbitmq
      - CLIENT_SERVICE_BASE_URL=http://clients-app:8080/api
    depends_on:
      - db
      - rabbitmq
      - clients-app

# Volumen para persistir los datos de la base de datos
volumes:
  postgres_data: